### ISSUE TITLE
very cool to see redpanda, let me know how to help

### ISSUE THREAD

**Issue by senior7515** [abaddon/burraco-vertx#40]
I didn't see a "discussions" section on the repo. Just wanted to stop by and say this is a really cool project. I found it when searching for redpanda.

**Comment by senior7515** [comment]
feel free to close :)

**Comment by abaddon** [comment]
thanks, at the moment it's on hold because I'm working on a library to manage [CQRS](https://github.com/abaddon/kotlin-cqrs). The plan is to use it here when it will be ready.

**Comment by senior7515** [comment]
cool, let me know if i can help. we hang out in the slack at vectorized.io/slack in case you want to drop by.
